language: php
dist: trusty

services:
  - docker

php:
    - '5.6'
    - '7.0'
    - '7.1'
    - '7.2'
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
        - php: hhvm
    include:
        - php: hhvm
        # define versions of MySQL and MariaDB to test against
        - env:
            - DB=mysql:5.5

git:
    depth: 1

cache:
    directories:
        - $HOME/.composer
        - $HOME/bin

sudo: required

before_install:
    #
    # install and init database (see matrix => include => env)
    #
    - ./travis/install-and-init-db.sh

    #
    # run tests
    #
    - mysql -e 'CREATE DATABASE IF NOT EXISTS testdb;'
    # Install composer packages, will also trigger dump-autoload
    - travis_retry composer install --no-interaction
    # Install coveralls.phar
    - wget -c -nc --retry-connrefused --tries=0 https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
    - chmod +x coveralls.phar
    - php coveralls.phar --version

script: vendor/bin/phpunit --coverage-clover gen/coverage/clover.xml

after_success:
    # Submit coverage report to Coveralls servers, see .coveralls.yml
    - travis_retry php coveralls.phar -v
