sudo: required

language: php

services:
  - docker

matrix:
    fast_finish: true
    include:
        #
        # Define versions of MySQL and MariaDB to test against.
        #
        # mysql 5.5
        - php: 5.6
          env: DB=mysql:5.5
        - php: 7.0
          env: DB=mysql:5.5
        - php: 7.1
          env: DB=mysql:5.5
        - php: 7.2
          env: DB=mysql:5.5
        # mysql 5.6
        - php: 5.6
          env: DB=mysql:5.6
        - php: 7.0
          env: DB=mysql:5.6
        - php: 7.1
          env: DB=mysql:5.6
        - php: 7.2
          env: DB=mysql:5.6
        # mysql 5.7
        - php: 5.6
          env: DB=mysql:5.7
        - php: 7.0
          env: DB=mysql:5.7
        - php: 7.1
          env: DB=mysql:5.7
        - php: 7.2
          env: DB=mysql:5.7
        # mysql 10.0
        - php: 5.6
          env: DB=mariadb:10.0
        - php: 7.0
          env: DB=mariadb:10.0
        - php: 7.1
          env: DB=mariadb:10.0
        - php: 7.2
          env: DB=mariadb:10.0
        # mariadb 10.1
        - php: 5.6
          env: DB=mariadb:10.1
        - php: 7.0
          env: DB=mariadb:10.1
        - php: 7.1
          env: DB=mariadb:10.1
        - php: 7.2
          env: DB=mariadb:10.1
        # mariadb 10.2
        - php: 5.6
          env: DB=mariadb:10.2
        - php: 7.0
          env: DB=mariadb:10.2
        - php: 7.1
          env: DB=mariadb:10.2
        - php: 7.2
          env: DB=mariadb:10.2
        # mariadb 10.3
        - php: 5.6
          env: DB=mariadb:10.3
        - php: 7.0
          env: DB=mariadb:10.3
        - php: 7.1
          env: DB=mariadb:10.3
        - php: 7.2
          env: DB=mariadb:10.3

git:
    depth: 1

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    #
    # install and init database (see matrix => include => env)
    #
    - ./.travis/install-and-init-db.sh

    #
    # setup and run tests
    #
    # Install composer packages, will also trigger dump-autoload
    - travis_retry composer install --no-interaction
    # Install coveralls.phar
    - wget -c -nc --retry-connrefused --tries=0 https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
    - chmod +x coveralls.phar
    - php coveralls.phar --version

script:
    - vendor/bin/phpunit --coverage-clover gen/coverage/clover.xml

after_success:
    # Submit coverage report to Coveralls servers, see .coveralls.yml
    - travis_retry php coveralls.phar -v
