language: php
dist: trusty

php:
    - '5.6'
    - '7.0'
    - '7.1'
    - '7.2'
    - nightly

env:
    - ARC2_DATABASE=mysql5.6

matrix:
    fast_finish: true
    include:
        - php: hhvm
    allow_failures:
        - php: nightly
        - php: hhvm

git:
    depth: 1

cache:
    directories:
        - $HOME/.composer
        - $HOME/bin

sudo: true

before_install:
    #
    # prepare database
    #
    - if [[ "$ARC2_DATABASE" == "mysql5.6" ]]; then ./scripts/tests/mysql_5.6_uninstall.sh; fi
    - if [[ "$ARC2_DATABASE" == "mysql5.6" ]]; then ./scripts/tests/mysql_5.6_install.sh; fi

    #
    # run tests
    #
    - mysql -e 'CREATE DATABASE IF NOT EXISTS testdb;'
    # Install composer packages, will also trigger dump-autoload
    - travis_retry composer install --no-interaction
    # Install coveralls.phar
    - wget -c -nc --retry-connrefused --tries=0 https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
    - chmod +x coveralls.phar
    - php coveralls.phar --version

script: vendor/bin/phpunit --coverage-clover gen/coverage/clover.xml

after_success:
    # Submit coverage report to Coveralls servers, see .coveralls.yml
    - travis_retry php coveralls.phar -v
